### ISSUE TITLE
Missing BOM

### ISSUE THREAD

**Issue by jdbaptista** [zinkwazi/traffic-pcb-sb#2]
Additionally, 3d models for LEDs would be a good addition to be able to see spacing.

**Comment by aidan-9880** [comment]
Check in hardware/kicad/jlcpcb/production_files. Last column has LCSC part numbers. 3D models are all in hardware/kicad/map_lbr.pretty, 0606.STEP should be the LED. Kicad probably "forgot" the correct path for the LED when I uploaded the files, it tends to do that.
