### ISSUE TITLE
Screen print tweaks

### ISSUE THREAD

**Issue by zinkwazi** [zinkwazi/traffic-pcb-sb#27]
- Remove the pointer lines from the current labels.
- Move Outside Open's label closer to the star and make the star bigger :) 
- Add labels for:
  - Long Beach
  - Glendale
  - Goleta :) 
  - Malibu
  - Santa Monica
  - Ventura
  - Anaheim
  - Remove the vertical South Western / Western avenue and label the 110.
  - Label Anacapa, and Santa Cruz islands

Don't be too concerned about being super accurate on the labels, this is a pretty broad strokes map.

**Comment by jdbaptista** [comment]
I'm not sure how the silkscreen for the roads was created nor how I can modify it, so I'll ask Aidan about if removing the vertical western avenue is possible easily. I will make a PR for the other stuff shortly

**Comment by aidan-9880** [comment]
I removed Western Ave in 30108bec5a281ee872067c4caef2b5d870d5c923. Should be good to close this.

**Comment by zinkwazi** [comment]
Nice!
