### ISSUE TITLE
Aesthetic changes to jumpers/test points

### ISSUE THREAD

**Issue by aidan-9880** [zinkwazi/traffic-pcb-sb#37]
Thinking about changing the wire jumpers to solder jumpers and moving them to the back of the board, just to keep the front side of the board looking clean. 

Also possible to do for the I2C/JTAG test points, but this might affect useability a little too much. Let me know what you think, this is a pretty easy change.

**Comment by jdbaptista** [comment]
That's a good idea as those are only for development. It should be easy enough to solder across a short enough gap for the JTAG jumpers. The I2C test points will be a little annoying to work with on the back, but I don't think we will need to use them as it's already known that I2C communication is working well.
