### ISSUE TITLE
Add an LED to indicate that an OTA update is available

### ISSUE THREAD

**Issue by jdbaptista** [zinkwazi/traffic-pcb-sb#43]
This will avoid me having to manually tell users (Greg) that an update is available. Alternatively we could implement forced auto updating, which may be better but not the best option for security purposes.

**Comment by aidan-9880** [comment]
Just fyi we're running out of IO pins. I think this would take up the last one, assuming we keep the photoresistor.

**Comment by jdbaptista** [comment]
If we have space, we should implement this as an LED in one of the matrices (could be a white LED), as well as the color key LEDs

**Comment by aidan-9880** [comment]
Good idea, definitely doable. Will do this for #32 as well.
